Fix snyk action - 6th try

diff --git a/.github/workflows/week3-hw.yml b/.github/workflows/week3-hw.yml
--- a/.github/workflows/week3-hw.yml
+++ b/.github/workflows/week3-hw.yml
@@ -29,6 +29,5 @@ jobs:
         run: echo "Security check is successful"
       - name: Exit if failure
         if: ${{ failure() }}
-        run: echo "Security check has failed"
-        run: exit 1
+        run: echo "Security check has failed" && exit 1
 
